---
name: Build packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: udondan/jsii
        with:
          fetch-depth: 1

      - name: Build Hugo page
        run: cd /workdir/app && ls -al
